<a href="https://colab.research.google.com/github/Jorge-742/TalenTech_Exercise_Practice/blob/main/Laboratorio_10_limpieza_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorio 10

In [ ]:
import pandas as pd

## Part 1.
Ejercicio de práctica 1.

Salud Digital y Análisis de Datos de Pacientes
Se tiene un conjunto de datos sobre pacientes que incluye nombre, edad, fecha de ingreso y resultados de pruebas. Algunos registros están incompletos o contienen errores.

In [ ]:
# Datos
data = {'Nombre': ['Carlos', 'Ana', 'Luis', 'Pedro', 'María', None],
        'Edad': [34, 29, None, 45, 25, 33],
        'Fecha_ingreso': ['2021-01-15', '2020/03/12', '2022-07-01', '2021/12/01', '2021-05-20', '2020-03-12'],
        'Resultado_prueba': ['Positivo','Negativo', 'Positivo', 'Positivo', 'Negativo','Negativo']}

In [ ]:
# Creación del dataframe
df = pd.DataFrame(data)
df.head(10)

   Nombre  Edad Fecha_ingreso Resultado_prueba
0  Carlos  34.0    2021-01-15         Positivo
1     Ana  29.0    2020/03/12         Negativo
2    Luis   NaN    2022-07-01         Positivo
3   Pedro  45.0    2021/12/01         Positivo
4   María  25.0    2021-05-20         Negativo
5    None  33.0    2020-03-12         Negativo

In [ ]:
# Limpieza de datos

#Dataframe original
print(df)

#Eliminación de datos faltantes en la columna nombre
print('\n Eliminicación de datos faltantes en la columna "Nombre"')
df = df.dropna(subset=['Nombre'])
print(df)

# Imputación de valores faltantes en la columna edad con el promedio de edad
print('\n Imputación de valores faltanes en la columna "Edad"')
df['Edad'] = df['Edad'].fillna(df['Edad'].mean())
print(df)

# Formateo de fecha
print('\n Formateo de fecha')
df['Fecha_ingreso'] = pd.to_datetime(df['Fecha_ingreso'].str.replace('/', "-"))
print(df)

   Nombre  Edad Fecha_ingreso Resultado_prueba
0  Carlos  34.0    2021-01-15         Positivo
1     Ana  29.0    2020/03/12         Negativo
2    Luis   NaN    2022-07-01         Positivo
3   Pedro  45.0    2021/12/01         Positivo
4   María  25.0    2021-05-20         Negativo
5    None  33.0    2020-03-12         Negativo

 Eliminicación de datos faltantes en la columna "Nombre"
   Nombre  Edad Fecha_ingreso Resultado_prueba
0  Carlos  34.0    2021-01-15         Positivo
1     Ana  29.0    2020/03/12         Negativo
2    Luis   NaN    2022-07-01         Positivo
3   Pedro  45.0    2021/12/01         Positivo
4   María  25.0    2021-05-20         Negativo

 Imputación de valores faltanes en la columna "Edad"
   Nombre   Edad Fecha_ingreso Resultado_prueba
0  Carlos  34.00    2021-01-15         Positivo
1     Ana  29.00    2020/03/12         Negativo
2    Luis  33.25    2022-07-01         Positivo
3   Pedro  45.00    2021/12/01         Positivo
4   María  25.00    2021-05-20         Negativo

 Formateo de fecha
   Nombre   Edad Fecha_ingreso Resultado_prueba
0  Carlos  34.00    2021-01-15         Positivo
1     Ana  29.00    2020-03-12         Negativo
2    Luis  33.25    2022-07-01         Positivo
3   Pedro  45.00    2021-12-01         Positivo
4   María  25.00    2021-05-20         Negativo

<ipython-input-35-03def36b3c63>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Edad'] = df['Edad'].fillna(df['Edad'].mean())
<ipython-input-35-03def36b3c63>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Fecha_ingreso'] = pd.to_datetime(df['Fecha_ingreso'].str.replace('/', "-"))



---

**Ejercicio 2.**

Comercio Electrónico y Recomendaciones Personalizadas
Se tiene un conjunto de datos sobre transacciones de clientes que incluye el ID del cliente, el producto comprado, la cantidad, el precio y la fecha de la transacción. Algunos registros tienen errores en los precios y fechas.

In [ ]:
# Datos

datos = {'Cliente ID': [1, 2, 3, 4, 5],
         'Producto' : ['A', 'B', 'C', 'D', 'E'],
         'Cantidad' : [10, 20, None, 5, 15],
         'Precio' : ['100', '200$','300', 'cuatrocientos','500'],
         'Fecha Transacción' : ['2023-01-15', '2023/02/20','2023-03-25','2023/04/30', '2023-05-10']}

df2 = pd.DataFrame(datos)
df2.head(10)

   Cliente ID Producto  Cantidad         Precio Fecha Transacción
0           1        A      10.0            100        2023-01-15
1           2        B      20.0           200$        2023/02/20
2           3        C       NaN            300        2023-03-25
3           4        D       5.0  cuatrocientos        2023/04/30
4           5        E      15.0            500        2023-05-10

In [ ]:
# Limpieza de datos

# 1. dataframe original
print('\n DataFrame original')
print(df2)

# 2. Imputación de valores faltantes
print('\n Imputación de valores faltantes')
df2['Cantidad'] = df2['Cantidad'].fillna(df2['Cantidad'].median())
print(df2)

# 3. correción de formato, remplazo de texto no numérico
# Conversión de tipo de dato, eliminación de caracteres no númericos.
print('\n correción de formato de Precio')
df2['Precio'] = df2['Precio'].str.replace('cuatrocientos', '400').str.replace(r'[^0-9]', '', regex=True).astype(float)
print(df2)

# 4. correción formato fecha.
print('\n Formateo de fecha')
df2['Fecha Transacción'] = pd.to_datetime(df2['Fecha Transacción'].str.replace('/', "-"))
print(df2)

 DataFrame original
   Cliente ID Producto  Cantidad         Precio Fecha Transacción
0           1        A      10.0            100        2023-01-15
1           2        B      20.0           200$        2023/02/20
2           3        C       NaN            300        2023-03-25
3           4        D       5.0  cuatrocientos        2023/04/30
4           5        E      15.0            500        2023-05-10

 Imputación de valores faltantes
   Cliente ID Producto  Cantidad         Precio Fecha Transacción
0           1        A      10.0            100        2023-01-15
1           2        B      20.0           200$        2023/02/20
2           3        C      12.5            300        2023-03-25
3           4        D       5.0  cuatrocientos        2023/04/30
4           5        E      15.0            500        2023-05-10

 correción de formato de Precio
   Cliente ID Producto  Cantidad  Precio Fecha Transacción
0           1        A      10.0   100.0        2023-01-15
1           2        B      20.0   200.0        2023/02/20
2           3        C      12.5   300.0        2023-03-25
3           4        D       5.0   400.0        2023/04/30
4           5        E      15.0   500.0        2023-05-10

 Formateo de fecha
   Cliente ID Producto  Cantidad  Precio Fecha Transacción
0           1        A      10.0   100.0        2023-01-15
1           2        B      20.0   200.0        2023-02-20
2           3        C      12.5   300.0        2023-03-25
3           4        D       5.0   400.0        2023-04-30
4           5        E      15.0   500.0        2023-05-10



---

**Ejercicio 3**

**Escenario:** eres un analista de datos en una pequeña empresa que está recopilando información sobre sus clientes.
El equipo de ventas te entrega un archivo con los siguientes datos:
- Nombre de los clientes
- Edad
- Correo electrónico
- País
- Género
- Número de visitas a la tienda

Sin embargo, cuando abres el archivo, te das cuenta de que hay problemas en los datos:
1. Valores faltantes: Algunos clientes no tienen información sobre su edad o correo electrónico.
2. Duplicados: Algunos clientes han sido registrados más de una vez.
3. Inconsistencias: Hay diferentes formas de escribir el género ("M", "Masculino", "F", "Femenino").
4. Errores tipográficos: El nombre de algunos países está en minúsculas o mal escrito.
5. Valores inválidos: Hay una edad registrada que parece imposible (200 años).

In [ ]:
data = """Nombre,Edad,Email,Pais,Genero,Visitas
Juan,25,juan@mail.com,colombia,M,5
Maria,30,maria@mail.com,Colombia,F,7
Pedro,,pedro@mail.com,Mexico,H,6
Ana,29,ana@mail.com,Argentina,F,4
Luisa,28,luisa@mail.com,Colombia,Femenino,8
Carlos,200,carlos@mail.com,Brazil,M,2
Juan,25,juan@mail.com,colombia,M,5"""

#Creacción de diccionario
lines = data.strip().split('\n')
header = lines[0].split(',')
rows = [line.split(',') for line in lines[1:]]
data_dict = {header[i]: [row[i] for row in rows] for i in range(len(header))}

# Creacción de dataframe
df = pd.DataFrame(data_dict)
df.head(10)

   Nombre Edad            Email       Pais    Genero Visitas
0    Juan   25    juan@mail.com   colombia         M       5
1   Maria   30   maria@mail.com   Colombia         F       7
2   Pedro        pedro@mail.com     Mexico         H       6
3     Ana   29     ana@mail.com  Argentina         F       4
4   Luisa   28   luisa@mail.com   Colombia  Femenino       8
5  Carlos  200  carlos@mail.com     Brazil         M       2
6    Juan   25    juan@mail.com   colombia         M       5

In [ ]:
# Limpieza de datos

# 0 conversion a tipos de datos
df['Edad'] = pd.to_numeric(df['Edad'], errors='coerce')
df['Visitas'] = pd.to_numeric(df['Visitas'], errors='coerce')
print('\n Conversion de tipos de datos')
print(df)

 Conversion de tipos de datos
   Nombre   Edad            Email       Pais    Genero  Visitas
0    Juan   25.0    juan@mail.com   colombia         M        5
1   Maria   30.0   maria@mail.com   Colombia         F        7
2   Pedro    NaN   pedro@mail.com     Mexico         H        6
3     Ana   29.0     ana@mail.com  Argentina         F        4
4   Luisa   28.0   luisa@mail.com   Colombia  Femenino        8
5  Carlos  200.0  carlos@mail.com     Brazil         M        2
6    Juan   25.0    juan@mail.com   colombia         M        5

In [ ]:
#1. Eliminación de duplicados
print('\n Eliminación de duplicados')
df = df.drop_duplicates()
print(df)

 Eliminación de duplicados
   Nombre   Edad            Email       Pais    Genero  Visitas
0    Juan   25.0    juan@mail.com   colombia         M        5
1   Maria   30.0   maria@mail.com   Colombia         F        7
2   Pedro    NaN   pedro@mail.com     Mexico         H        6
3     Ana   29.0     ana@mail.com  Argentina         F        4
4   Luisa   28.0   luisa@mail.com   Colombia  Femenino        8
5  Carlos  200.0  carlos@mail.com     Brazil         M        2

In [ ]:
# 2 correción de valores
print('\n Correción de valores')
df.loc[df['Edad'] > 100, 'Edad'] = df['Edad'].mean()
print(df)

 Correción de valores
   Nombre  Edad            Email       Pais    Genero  Visitas
0    Juan  25.0    juan@mail.com   colombia         M        5
1   Maria  30.0   maria@mail.com   Colombia         F        7
2   Pedro   NaN   pedro@mail.com     Mexico         H        6
3     Ana  29.0     ana@mail.com  Argentina         F        4
4   Luisa  28.0   luisa@mail.com   Colombia  Femenino        8
5  Carlos  62.4  carlos@mail.com     Brazil         M        2

In [ ]:
# 3. relleno de valores faltantes
df['Edad'] = df['Edad'].fillna(df['Edad'].mean())
print('\n Relleno de valores faltantes')
print(df)

 Relleno de valores faltantes
   Nombre   Edad            Email       Pais    Genero  Visitas
0    Juan  25.00    juan@mail.com   colombia         M        5
1   Maria  30.00   maria@mail.com   Colombia         F        7
2   Pedro  34.88   pedro@mail.com     Mexico         H        6
3     Ana  29.00     ana@mail.com  Argentina         F        4
4   Luisa  28.00   luisa@mail.com   Colombia  Femenino        8
5  Carlos  62.40  carlos@mail.com     Brazil         M        2

In [ ]:

# 4. Estandarización de Columnas

# 1. estandarización de la columna Email
print('\n Estandarización de columna Email')
df['Email'] = df['Email'].str.lower()
print(df)

# 2. Estandarización columna país
print('\n Estandarización de columna País')
df['Pais'] = df['Pais'].str.capitalize().str.replace('Brazil', 'Brasil')
print(df)

# 3. Estandarización columna género
print('\n Estandarización de columna Género')
df['Genero'] = df['Genero'].str.replace('M', 'Masculino').str.replace('F', 'Femenino').str.replace('H', 'Masculino').str.replace('Femeninoemenino', 'Femenino')
print(df)

 Estandarización de columna Email
   Nombre   Edad            Email       Pais    Genero  Visitas
0    Juan  25.00    juan@mail.com   colombia         M        5
1   Maria  30.00   maria@mail.com   Colombia         F        7
2   Pedro  34.88   pedro@mail.com     Mexico         H        6
3     Ana  29.00     ana@mail.com  Argentina         F        4
4   Luisa  28.00   luisa@mail.com   Colombia  Femenino        8
5  Carlos  62.40  carlos@mail.com     Brazil         M        2

 Estandarización de columna País
   Nombre   Edad            Email       Pais    Genero  Visitas
0    Juan  25.00    juan@mail.com   Colombia         M        5
1   Maria  30.00   maria@mail.com   Colombia         F        7
2   Pedro  34.88   pedro@mail.com     Mexico         H        6
3     Ana  29.00     ana@mail.com  Argentina         F        4
4   Luisa  28.00   luisa@mail.com   Colombia  Femenino        8
5  Carlos  62.40  carlos@mail.com     Brasil         M        2

 Estandarización de columna Género
   Nombre   Edad            Email       Pais     Genero  Visitas
0    Juan  25.00    juan@mail.com   Colombia  Masculino        5
1   Maria  30.00   maria@mail.com   Colombia   Femenino        7
2   Pedro  34.88   pedro@mail.com     Mexico  Masculino        6
3     Ana  29.00     ana@mail.com  Argentina   Femenino        4
4   Luisa  28.00   luisa@mail.com   Colombia   Femenino        8
5  Carlos  62.40  carlos@mail.com     Brasil  Masculino        2

In [ ]:
#almanecamiento de la limpieza de datos en una nueva variable.
df_final = df

print('\n DataFrame final')
print(df_final)
df_final.to_csv('df_final.csv', index=False)
df_final.dtypes

 DataFrame final
   Nombre   Edad            Email       Pais     Genero  Visitas
0    Juan  25.00    juan@mail.com   Colombia  Masculino        5
1   Maria  30.00   maria@mail.com   Colombia   Femenino        7
2   Pedro  34.88   pedro@mail.com     Mexico  Masculino        6
3     Ana  29.00     ana@mail.com  Argentina   Femenino        4
4   Luisa  28.00   luisa@mail.com   Colombia   Femenino        8
5  Carlos  62.40  carlos@mail.com     Brasil  Masculino        2

Nombre      object
Edad       float64
Email       object
Pais        object
Genero      object
Visitas      int64
dtype: object

In [ ]:
data_final = pd.read_csv('df_final.csv')
data_final.head(10)

   Nombre   Edad            Email       Pais     Genero  Visitas
0    Juan  25.00    juan@mail.com   Colombia  Masculino        5
1   Maria  30.00   maria@mail.com   Colombia   Femenino        7
2   Pedro  34.88   pedro@mail.com     Mexico  Masculino        6
3     Ana  29.00     ana@mail.com  Argentina   Femenino        4
4   Luisa  28.00   luisa@mail.com   Colombia   Femenino        8
5  Carlos  62.40  carlos@mail.com     Brasil  Masculino        2